#whitelist
branches:
    only:
        - develop

language: cpp

compiler: clang

before_install:
    - echo "yes" | sudo apt-add-repository ppa:mapnik/boost-backports-1-54
    - sudo apt-get update -qq
    - sudo apt-get install -qq libboost-all-dev

script: mkdir build && cd build && cmake -DBOOST_ROOT=/usr/local .. && make && make test


