#whitelist
branches:
    only:
        - develop

language: cpp

compiler: gcc

before_install:
    - echo "yes" | sudo apt-add-repository ppa:boost-latest
    - echo "yes" | sudo apt-add-repository ppa:mapnik/boost-backports-1-54
    - echo "yes" | sudo apt-add-repository ppa:ubuntu-toolchain-r/test
    - sudo apt-get clean -qq
    - sudo apt-get update -qq
    - sudo apt-get install -qq gcc-4.8 g++-4.8
    - export CC="gcc-4.8"
    - export CXX="gcc-4.8"
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50

      #- sudo apt-get install -qq libboost1.55-all-dev

install:
    - export CXX="g++-4.8"
    - export CC="gcc-4.8"

script: travis_wait mkdir build && cd build && cmake -DFETCH_BOOST=TRUE .. && make && make test


